### ISSUE TITLE
Google places Api

### ISSUE THREAD

**Issue by dianaserban** [ucv/My-Superstar#23]
For the moment, there are not many restaurants or reviews. Fortunately, Google Places offers an API to retrieve restaurants and reviews! Use it to display additional restaurants and reviews on your map so you don't have to use only your JSON file. Here's their documentation: https://developers.google.com/places/web-service/details

**Comment by ucv** [comment]
See Issue #7,
Can fix only whit php.

**Comment by ucv** [comment]
Can fix only w php

See issue #13
